[tasks.framework_build]
command = "pnpm"
args = ["-C", "packages/framework", "build"]


[tasks.framework_live_rebuild]
command = "pnpm"
args = ["-C", "packages/framework", "watch"]


[tasks.gateway_devserver]
command = "cargo"
args = ["leptos", "watch"]


[tasks.devserver]
run_task = { name = [
	"framework_live_rebuild",
	"gateway_devserver",
], parallel = true }
